name: hirome_rental_owner_web
description: ひろめ市場 食器レンタルシステム - 管理者専用

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  fluent_ui: ^4.11.2
  flutter_spinkit: ^5.2.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  syncfusion_flutter_datagrid_export: ^28.2.11
  syncfusion_localizations: ^28.2.11
  file_picker: ^9.0.2
  image_picker: ^1.1.2
  calendar_date_picker2: ^1.1.9
  month_picker_dialog: ^6.0.3
  csv: ^6.0.0
  pdf: ^3.11.3
  universal_html: ^2.2.4
  file_selector: ^1.0.3
  url_launcher: ^6.3.1

  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: SourceHanSansJP-Bold
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Bold.otf
    - family: SourceHanSansJP-Regular
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Regular.otf