name: hirome_rental_owner_web
description: ひろめ市場 食器レンタルシステム - 管理者専用

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  fluent_ui: ^4.6.2
  flutter_spinkit: ^5.2.0
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  syncfusion_flutter_datagrid_export: ^21.1.35-beta
  syncfusion_localizations: ^21.2.5
  file_picker: ^5.3.2
  image_picker: ^1.0.0
  calendar_date_picker2: ^0.5.2
  badges: ^3.1.1
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: SourceHanSansJP-Bold
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Bold.otf
    - family: SourceHanSansJP-Regular
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Regular.otf